// Additional resume skill keywords (merged into kSkillSuggestionPool). Keep unique vs core list.

const List<String> kSkillSuggestionExtra = [
  'AB Testing',
  'Active Directory',
  'Adobe Creative Suite',
  'Adobe XD',
  'Airbyte',
  'Alpine.js',
  'Amazon RDS',
  'Amazon Redshift',
  'Android Studio',
  'AngularJS',
  'Ansible Tower',
  'Ant Design',
  'Apache Beam',
  'Apache Hive',
  'Apache NiFi',
  'Apache Solr',
  'Apache Spark',
  'Apache Superset',
  'API Design',
  'API Gateway',
  'App Store Connect',
  'Appium',
  'Argo CD',
  'ArkTS',
  'Art Direction',
  'ASP.NET Core',
  'Athena (AWS)',
  'Augmented Reality',
  'Auth0',
  'Axios',
  'Backbone.js',
  'Balsamiq',
  'Bazel',
  'BIRT Reporting',
  'Bitbucket',
  'Blockchain',
  'BPMN',
  'BrowserStack',
  'Bug Bounty',
  'BullMQ',
  'Burp Suite',
  'Camunda',
  'Capacitor',
  'Carbon Design System',
  'Chai',
  'Chatbot Development',
  'Chef (DevOps)',
  'Chrome DevTools',
  'Cisco Networking',
  'CleverTap',
  'ClickHouse',
  'Cloudflare',
  'CloudFormation',
  'CMake',
  'COBOL',
  'CockroachDB',
  'ColdFusion',
  'Competitive Analysis',
  'Computer Networks',
  'Computer Vision',
  'Confluence',
  'Content Strategy',
  'Contract Negotiation',
  'Corda',
  'Cordova',
  'Cosmos DB',
  'Crystal',
  'CUDA',
  'Customer Development',
  'Cypress',
  'Dagger',
  'Dart',
  'Data Governance',
  'Data Lake',
  'Data Mining',
  'Data Structures and Algorithms',
  'Database Management Systems',
  'dbt',
  'DDD',
  'Debian',
  'Decision Trees',
  'Debugging',
  'Design Thinking',
  'Digital Marketing',
  'Digital Ocean',
  'Django REST Framework',
  'DNS Management',
  'Drone CI',
  'Dropwizard',
  'DuckDB',
  'Eclipse IDE',
  'Elastic Beanstalk',
  'Electron',
  'emacs',
  'Embedded C',
  'Entity Framework',
  'Ethers.js',
  'Ethical Hacking',
  'FastAPI',
  'Fastlane',
  'Fauna DB',
  'Feature Flags',
  'Fintech',
  'Firestore',
  'Fleet Management',
  'FlutterFlow',
  'Font Awesome',
  'Forensic Analysis',
  'Fortran',
  'FPGA',
  'Framer',
  'Freelance Management',
  'Functional Programming',
  'Game Development',
  'Gemini API',
  'GIS',
  'Git Flow',
  'Git LFS',
  'Gloo Edge',
  'GNU Make',
  'GnuPG',
  'GORM',
  'Growth Hacking',
  'HAProxy',
  'Hardhat',
  'Haxe',
  'Helm',
  'HFSS',
  'HRM Systems',
  'HubSpot',
  'Hugging Face',
  'Hyper-V',
  'HyperLedger',
  'Identity Management',
  'Incident Response',
  'Infrastructure as Code',
  'IntelliJ IDEA',
  'Invision Studio',
  'Ionic',
  'IoT Development',
  'IP Networking',
  'Istio',
  'Jamstack',
  'Jasper Reports',
  'JavaBeans',
  'Java EE',
  'JDBC',
  'JHipster',
  'Joomla',
  'jQuery',
  'JSF',
  'JSON Web Tokens',
  'JUnit Platform',
  'JWT',
  'Kafka Streams',
  'Kali Linux',
  'Kanban',
  'Karate DSL',
  'Kendo UI',
  'Kibana',
  'Knockout.js',
  'Ktor',
  'Label Studio',
  'LangChain',
  'launchd',
  'Leadership Development',
  'Lit',
  'Load Balancing',
  'Lodash',
  'Logstash',
  'LookML',
  'Lucidchart',
  'Lucene',
  'LuaJIT',
  'Lumen',
  'macOS Administration',
  'Makefile',
  'Material UI',
  'MATLAB Simulink',
  'MemSQL',
  'Mercurial',
  'Mesos',
  'Meteor.js',
  'MFA',
  'MicroPython',
  'MikroTik',
  'Miro',
  'MJML',
  'Mocha',
  'Mockito',
  'Modbus',
  'Monolith Refactoring',
  'MSSQL',
  'Multithreading',
  'Mustache.js',
  'MyBatis',
  'nano',
  'NATS Streaming',
  'Neo4j',
  'NestJS',
  'NetBeans',
  'Netlify',
  'Network Security',
  'New Relic',
  'NextAuth',
  'NFC',
  'Nix',
  'Nomad',
  'NuGet',
  'NumPy',
  'Nuxt.js',
  'OAuth2',
  'Objective-C',
  'Object-Oriented Programming',
  'Observability',
  'Odoo',
  'OKR Planning',
  'Okta',
  'OmniFocus',
  'Open CASCADE',
  'OpenCV',
  'OpenFGA',
  'OpenLayers',
  'OpenLDAP',
  'OpenSearch',
  'OpenStack',
  'OpenTelemetry',
  'OpenTracing',
  'OpenVPN',
  'Operating Systems',
  'Oracle EBS',
  'Organic SEO',
  'ORM',
  'Packer',
  'Pandas (Python)',
  'Parcel',
  'Penetration Testing',
  'Phalcon',
  'Phaser',
  'Phoenix LiveView',
  'Photogrammetry',
  'PingFederate',
  'PixiJS',
  'Playwright',
  'Plotly',
  'PMBOK',
  'Podman',
  'Polymer.js',
  'PostCSS',
  'Postgis',
  'Pow',
  'Power Apps',
  'Power Automate',
  'Power Platform',
  'Prettier',
  'Prisma ORM',
  'Private Equity',
  'Process Improvement',
  'Program Management',
  'Proofreading',
  'Protractor',
  'Proxmox',
  'Pulumi',
  'PureScript',
  'PyTorch Lightning',
  'QA Automation',
  'Qlik Sense',
  'Qt Creator',
  'Quarkus',
  'Quasar',
  'R Shiny',
  'Racket',
  'Ramda',
  'Rancher',
  'RBAC',
  'ReDoc',
  'RealityKit',
  'Red Hat OpenShift',
  'Reinforcement Learning',
  'Render.com',
  'RenPy',
  'Requirements Engineering',
  'Retrofit',
  'Reverse Engineering',
  'Revit',
  'Riak',
  'Robot Framework',
  'Rocket.Chat',
  'Rollup',
  'ROS',
  'RStudio',
  'RxJava',
  'RxJS',
  'Sales Cloud',
  'SAM Local',
  'SAML 2.0',
  'SASS Architecture',
  'Sails.js',
  'SameSite Cookies',
  'SAP Fiori',
  'SAP HANA',
  'SAR Processing',
  'Sass/SCSS',
  'SDL Trados',
  'SDR',
  'Semantic HTML',
  'SendGrid',
  'Service Mesh',
  'ServiceNow',
  'Shadow DOM',
  'Shopify Liquid',
  'Signal Processing',
  'Sinatra',
  'Single Sign-On',
  'SketchUp',
  'Smart Contracts',
  'Snow CLI',
  'SOC 2',
  'Socket.io',
  'Software Licensing',
  'SolidWorks',
  'SonarQube',
  'Sorbet',
  'Spacy',
  'Specflow',
  'Splunk',
  'Spring Cloud',
  'Spring MVC',
  'Spring Security',
  'SQLAlchemy',
  'SQLite Browser',
  'Squarespace',
  'SSR',
  'Starlette',
  'Storytelling',
  'Stripe API',
  'Structured Cabling',
  'Styled Components',
  'Subversion',
  'Succession Planning',
  'Svelte Stores',
  'Swagger UI',
  'Swift Package Manager',
  'Symfony Console',
  'Synapse Analytics',
  'System Design Fundamentals',
  'Tableau Prep',
  'Tarantool',
  'Technical Recruiting',
  'Telecommunications',
  'TensorBoard',
  'Teradata',
  'TestContainers',
  'TestNG',
  'Tesseract OCR',
  'Theming',
  'Thrift',
  'tiktoken',
  'TinyML',
  'TOML',
  'Tomcat',
  'TorchScript',
  'Traefik Mesh',
  'Training Delivery',
  'Travis CI',
  'Trello',
  'Trino',
  'TurboRepo',
  'Twilio',
  'TypeORM',
  'Ubuntu Server',
  'Uikit (PHP)',
  'Umbraco',
  'UML',
  'Underscore.js',
  'Unity 3D',
  'Unreal Engine',
  'UPS Systems',
  'Vault (HashiCorp)',
  'Vercel',
  'Video Editing',
  'Virtualization',
  'Visio',
  'Vitest',
  'VMware',
  'Voice UI',
  'Volt',
  'VPN Administration',
  'vSphere',
  'Vue Router',
  'Vuex',
  'WASM',
  'Waterfall Model',
  'Web Accessibility',
  'WebAssembly',
  'WebDriver',
  'Webpack 5',
  'WebRTC',
  'WebSocket',
  'Wijmo',
  'Win32 API',
  'Windows Server',
  'Wireshark',
  'Wix',
  'Word2Vec',
  'Workspace ONE',
  'WS-Security',
  'Xamarin.Forms',
  'Xcode Instruments',
  'XenServer',
  'XML Schema',
  'YAML Lint',
  'YARN Workspaces',
  'Yocto Project',
  'YouTrack',
  'ZBrush',
  'Zeplin',
  'Zero Trust',
  'Zig',
  'ZIO',
  'Zustand',
];
