// Everyday and cross-industry skills people add to a resume: care work,
// teaching, trades, logistics, hospitality, retail, admin, HR, sales,
// creative work, field work and soft skills.
// Merged into kSkillSuggestionPool; entries here are unique against the
// core, extra and professions lists.

const List<String> kSkillSuggestionEveryday = [
  // Healthcare & care
  'Advanced Cardiac Life Support',
  'Basic Life Support',
  'Bedside Manner',
  'Blood Pressure Monitoring',
  'Care Planning',
  'Caregiving',
  'Case Management',
  'Childcare',
  'Counselling',
  'CPR',
  'CPT Coding',
  'Dental Assisting',
  'Diabetes Management',
  'Elderly Care',
  'Electronic Health Records',
  'First Aid',
  'HIPAA Compliance',
  'Home Health Care',
  'Immunisation',
  'IV Therapy',
  'Laboratory Testing',
  'Maternity Care',
  'Medical Coding',
  'Medication Administration',
  'Mental Health Support',
  'Nursing',
  'Nutrition Counselling',
  'Occupational Therapy',
  'Paediatric Care',
  'Palliative Care',
  'Patient Care',
  'Patient Charting',
  'Pharmacy Dispensing',
  'Phlebotomy',
  'Physiotherapy',
  'Prescription Review',
  'Radiology',
  'Rehabilitation Therapy',
  'Specimen Collection',
  'Speech Therapy',
  'Sterilisation Technique',
  'Telemedicine',
  'Triage',
  'Ultrasound Imaging',
  'Veterinary Assisting',
  'Vital Signs Monitoring',
  'Wound Care',
  'X-Ray Positioning',
  // Education & training
  'Academic Advising',
  'Assessment Design',
  'Behaviour Management',
  'Blackboard',
  'Blended Learning',
  'Classroom Management',
  'Coaching',
  'Corporate Training',
  'Course Authoring',
  'Curriculum Development',
  'E-Learning Design',
  'Early Childhood Education',
  'Educational Technology',
  'Exam Preparation',
  'Google Classroom',
  'Grading',
  'Individualised Education Plans',
  'Learning Management Systems',
  'Lesson Planning',
  'Montessori Method',
  'Moodle',
  'Onboarding Training',
  'Phonics Instruction',
  'Special Education',
  'STEM Instruction',
  'Student Assessment',
  'Student Counselling',
  'Teaching',
  'Tutoring',
  // Skilled trades & manufacturing
  'Appliance Repair',
  'Arc Welding',
  'Assembly Line Operation',
  'Auto Body Repair',
  'AutoCAD',
  'Automotive Repair',
  'Brazing',
  'Bricklaying',
  'Calibration',
  'Carpentry',
  'CATIA',
  'CNC Machining',
  'CNC Programming',
  'Concrete Finishing',
  'Crane Operation',
  'Dimensional Inspection',
  'Drywall Installation',
  'Electrical Panel Wiring',
  'Electrical Troubleshooting',
  'Electrical Wiring',
  'Engine Diagnostics',
  'Fabrication',
  'Facility Maintenance',
  'Flooring Installation',
  'Forklift Operation',
  'Fusion 360',
  'Gardening',
  'Glazing',
  'Grinding',
  'Groundskeeping',
  'Heavy Equipment Operation',
  'HVAC Installation',
  'Hydraulics',
  'Injection Moulding',
  'Instrumentation',
  'Irrigation Systems',
  'Joinery',
  'Landscaping',
  'Lathe Operation',
  'Machine Operation',
  'Masonry',
  'MIG Welding',
  'Milling',
  'Non-Destructive Testing',
  'Painting and Decorating',
  'Pest Control',
  'Pipefitting',
  'PLC Programming',
  'Plumbing',
  'Pneumatics',
  'Predictive Maintenance',
  'Refrigeration',
  'Rigging',
  'Roofing',
  'SCADA Systems',
  'Scaffolding',
  'Sheet Metal Work',
  'Small Engine Repair',
  'Solar Panel Installation',
  'Soldering',
  'Technical Drawing',
  'TIG Welding',
  'Tool and Die',
  'Tyre Fitting',
  'Vehicle Maintenance',
  'Welding',
  // Safety & compliance
  'Corrective and Preventive Action',
  'Emergency Response',
  'Environmental Compliance',
  'Evacuation Planning',
  'Fire Safety',
  'Food Safety',
  'HACCP',
  'Hazard Identification',
  'Incident Investigation',
  'ISO 27001',
  'Kaizen',
  'Lean Six Sigma',
  'OSHA Compliance',
  'Personal Protective Equipment',
  'Quality Assurance Audits',
  'Risk Assessment',
  'Safety Audits',
  'Six Sigma Green Belt',
  'Waste Management',
  'Workplace Safety',
  // Logistics & warehouse
  'Barcode Scanning',
  'Cold Chain Management',
  'Courier Operations',
  'Customs Documentation',
  'Cycle Counting',
  'Delivery Tracking',
  'Dispatch Scheduling',
  'Freight Forwarding',
  'Goods Inward',
  'Import Export Documentation',
  'Inventory Management',
  'Last Mile Delivery',
  'Logistics Coordination',
  'Material Handling',
  'Order Picking',
  'Packing and Dispatch',
  'Procurement',
  'RFID Systems',
  'Route Planning',
  'Shipping and Receiving',
  'Stock Control',
  'Supplier Coordination',
  'Vendor Negotiation',
  'Warehouse Management Systems',
  'Warehouse Operations',
  // Hospitality & food service
  'Allergen Awareness',
  'Baking',
  'Banquet Service',
  'Bar Inventory',
  'Barista Skills',
  'Bartending',
  'Check-In and Check-Out',
  'Coffee Brewing',
  'Concierge Services',
  'Cooking',
  'Event Catering',
  'Food Plating',
  'Food Preparation',
  'Front Desk Operations',
  'Grill Operation',
  'Guest Relations',
  'Hotel Reservations',
  'Housekeeping',
  'Itinerary Planning',
  'Kitchen Hygiene',
  'Kitchen Management',
  'Laundry Operations',
  'Menu Planning',
  'Mixology',
  'Order Taking',
  'Pastry Making',
  'Point of Sale Systems',
  'Portion Control',
  'Recipe Development',
  'Table Service',
  'Tourism Coordination',
  'Travel Booking',
  'Waiting Tables',
  'Wine Knowledge',
  // Retail & customer service
  'Billing Support',
  'Call Handling',
  'Cashiering',
  'Complaint Resolution',
  'Cross-Selling',
  'Customer Retention',
  'Customer Satisfaction Surveys',
  'Email Support',
  'Escalation Handling',
  'Inbound Calls',
  'Live Chat Support',
  'Loss Prevention',
  'Outbound Calls',
  'Planogram Compliance',
  'Product Demonstration',
  'Product Display',
  'Queue Management',
  'Returns Processing',
  'Service Level Agreements',
  'Stock Replenishment',
  'Store Opening and Closing',
  'Ticketing Systems',
  'Upselling',
  'Visual Merchandising',
  // Finance, accounting & admin
  'Audit Support',
  'Billing',
  'Budget Tracking',
  'Cash Flow Management',
  'Cost Control',
  'Credit Control',
  'Data Entry',
  'Debt Recovery',
  'Document Control',
  'Expense Reporting',
  'Filing Systems',
  'Front Office Management',
  'Google Workspace',
  'GST Filing',
  'Income Tax Filing',
  'Insurance Claims',
  'Internal Controls',
  'Inventory of Office Supplies',
  'Mail Handling',
  'Meeting Coordination',
  'Microsoft Office',
  'Minute Taking',
  'Month End Close',
  'Office Administration',
  'Payroll Compliance',
  'Petty Cash Handling',
  'Pivot Tables',
  'QuickBooks',
  'Records Management',
  'Sage Accounting',
  'Spreadsheet Modelling',
  'Tally ERP',
  'Tax Planning',
  'TDS Filing',
  'Travel Coordination',
  'Typing Speed',
  'VAT Returns',
  'VLOOKUP',
  'Xero',
  'Year End Close',
  'Zoho Books',
  // HR & recruitment
  'Applicant Tracking Systems',
  'Appraisal Cycles',
  'Attendance Management',
  'Benefits Administration',
  'Campus Hiring',
  'Compensation Benchmarking',
  'Diversity and Inclusion',
  'Employee Offboarding',
  'Employee Onboarding',
  'Exit Interviews',
  'Grievance Handling',
  'Headhunting',
  'HR Policy Writing',
  'Interviewing',
  'Job Posting',
  'Labour Law Compliance',
  'Leave Management',
  'Recruitment',
  'Talent Sourcing',
  'Technical Interviewing',
  // Sales & marketing
  'Account Management',
  'Blog Writing',
  'Brand Management',
  'Campaign Planning',
  'Client Relationship Management',
  'Cold Calling',
  'Competitor Analysis',
  'Consultative Selling',
  'Content Writing',
  'Conversion Optimisation',
  'Customer Segmentation',
  'Distributor Management',
  'Editing',
  'Key Account Management',
  'Keyword Research',
  'Marketing Strategy',
  'Media Buying',
  'Paid Search',
  'Press Release Writing',
  'Product Knowledge',
  'Prospecting',
  'Retail Distribution',
  'Sales Forecasting',
  'Sales Pipeline Management',
  'Search Engine Optimisation',
  'Social Media Management',
  'Tender Preparation',
  'Trade Show Management',
  // Creative & media
  '2D Animation',
  '3D Modelling',
  '3D Rendering',
  'Animation',
  'Audio Editing',
  'Brand Identity Design',
  'Colour Grading',
  'Digital Illustration',
  'Fashion Design',
  'Graphic Design',
  'Illustration',
  'Interior Design',
  'Jewellery Design',
  'Layout Design',
  'Live Streaming',
  'Logo Design',
  'Motion Graphics',
  'Packaging Design',
  'Pattern Making',
  'Photo Retouching',
  'Photography',
  'Portrait Photography',
  'Prepress',
  'Print Production',
  'Product Photography',
  'Scriptwriting',
  'Set Design',
  'Sound Design',
  'Textile Design',
  'Typography',
  'Videography',
  // Security, driving & field work
  'Access Control',
  'Alarm Response',
  'CCTV Monitoring',
  'Chauffeur Services',
  'Commercial Driving',
  'Crowd Control',
  'Defensive Driving',
  'Delivery Driving',
  'Field Service',
  'GPS Navigation',
  'Incident Reporting',
  'Installation Services',
  'Loss Prevention Investigation',
  'Meter Reading',
  'On-Site Troubleshooting',
  'Route Navigation',
  'Security Patrolling',
  'Site Inspection',
  'Site Supervision',
  'Surveying',
  'Vehicle Inspection',
  'Visitor Management',
  // Agriculture & environment
  'Carbon Accounting',
  'Crop Management',
  'Dairy Operations',
  'Environmental Monitoring',
  'Farm Equipment Operation',
  'Fertiliser Application',
  'Forestry',
  'Greenhouse Operations',
  'Harvest Planning',
  'Horticulture',
  'Irrigation Management',
  'Livestock Care',
  'Nursery Management',
  'Organic Farming',
  'Poultry Management',
  'Recycling Programmes',
  // Soft skills
  'Client Communication',
  'Cultural Awareness',
  'Customer Focus',
  'Delegation',
  'Empathy',
  'Flexibility',
  'Initiative',
  'Organisation',
  'People Management',
  'Persuasion',
  'Prioritisation',
  'Reliability',
  'Remote Collaboration',
  'Resilience',
  'Self Motivation',
  'Stress Management',
  'Verbal Communication',
];
