// Curated pool for the Skills step typeahead (offline; no network).
// Prefix matches are ranked before substring matches; results are capped.

import 'skill_suggestions_extra.dart';
import 'skill_suggestions_professions.dart';

const List<String> kSkillSuggestionCore = [
  '.NET',
  'AWS',
  'Agile',
  'Algorithm Design',
  'Analytical Thinking',
  'Android',
  'Angular',
  'Ansible',
  'Apache Airflow',
  'Apache Kafka',
  'Apollo GraphQL',
  'Asana',
  'Astro',
  'Azure',
  'Azure DevOps',
  'Bash',
  'BigQuery',
  'Bootstrap',
  'C',
  'C#',
  'C++',
  'CI/CD',
  'CMS',
  'CRM',
  'CSS',
  'Cassandra',
  'CircleCI',
  'Cloud Architecture',
  'Couchbase',
  'Cross-functional Collaboration',
  'Customer Success',
  'Cybersecurity',
  'D3.js',
  'Data Analysis',
  'Data Engineering',
  'Data Modeling',
  'Data Visualization',
  'Databricks',
  'Denodo',
  'Design Systems',
  'DevOps',
  'Django',
  'Docker',
  'Domain-Driven Design',
  'DynamoDB',
  'ELK Stack',
  'ETL',
  'Elasticsearch',
  'Elixir',
  'Elm',
  'Embedded Systems',
  'Ember.js',
  'English (Professional)',
  'Erlang',
  'Express.js',
  'Figma',
  'Firebase',
  'Flask',
  'Fluentd',
  'Flutter',
  'Gatsby',
  'Git',
  'GitHub',
  'GitHub Actions',
  'GitLab',
  'Go',
  'Google Analytics',
  'Google Cloud',
  'Gradle',
  'GraphQL',
  'Groovy',
  'Grafana',
  'Hadoop',
  'Haskell',
  'Heroku',
  'Hibernate',
  'Hive',
  'HTML',
  'HTTP/REST',
  'Hugo',
  'IAM',
  'IBM Cloud',
  'Illustrator',
  'Information Security',
  'InfluxDB',
  'Integration Testing',
  'InVision',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jest',
  'Jira',
  'Julia',
  'JUnit',
  'JUnit 5',
  'K8s',
  'Keras',
  'Keycloak',
  'Kotlin',
  'Kubernetes',
  'LDAP',
  'LLM Prompting',
  'Laravel',
  'Linux',
  'Logistics',
  'Looker',
  'Lua',
  'MLflow',
  'Machine Learning',
  'MariaDB',
  'MATLAB',
  'Maven',
  'Mentoring',
  'Microservices',
  'Microsoft 365',
  'MongoDB',
  'MySQL',
  'NATS',
  'NGINX',
  'NLP',
  'Next.js',
  'Node.js',
  'Nuxt',
  'OCaml',
  'OAuth',
  'OIDC',
  'OpenAPI',
  'OpenShift',
  'Oracle DB',
  'pandas',
  'Perl',
  'Phoenix',
  'Photoshop',
  'PHP',
  'PostgreSQL',
  'Postman',
  'Power BI',
  'PowerShell',
  'Product Management',
  'Project Management',
  'Prometheus',
  'Protobuf',
  'Public Speaking',
  'Puppet',
  'PySpark',
  'PyTest',
  'Python',
  'SQL',
  'Qt',
  'R',
  'RabbitMQ',
  'React',
  'React Native',
  'Redis',
  'Redux',
  'Requirements Gathering',
  'Ruby',
  'Ruby on Rails',
  'Rust',
  'SAML',
  'SAP',
  'SAS',
  'SDK Development',
  'SEO',
  'SOAP',
  'SQLite',
  'SSL/TLS',
  'SSO',
  'Salesforce',
  'Scala',
  'Scikit-learn',
  'Scrum',
  'SecOps',
  'Selenium',
  'Serverless',
  'Shopify',
  'Sketch',
  'Snowflake',
  'Solr',
  'Solidity',
  'Spring',
  'Spring Boot',
  'Stakeholder Management',
  'Storybook',
  'Strapi',
  'Stream Processing',
  'Svelte',
  'SvelteKit',
  'Swift',
  'SwiftUI',
  'Symfony',
  'Systems Design',
  'Tailwind CSS',
  'Team Leadership',
  'Technical Writing',
  'TensorFlow',
  'Terraform',
  'Test Automation',
  'Three.js',
  'Traefik',
  'TypeScript',
  'UIKit',
  'Unix',
  'User Research',
  'VBA',
  'VHDL',
  'Verilog',
  'Vert.x',
  'Vue.js',
  'Webpack',
  'Wireframing',
  'WordPress',
  'Workday',
  'Xamarin',
  'Xcode',
  'XPath',
  'XSLT',
  'YAML',
  'Zapier',
  'Zendesk',
  'gRPC',
  'iOS',
  'macOS',
  'npm',
  'yarn',
];

/// Core + extended + cross-industry lists (deduped case-insensitively when matching).
const List<String> kSkillSuggestionPool = [
  ...kSkillSuggestionCore,
  ...kSkillSuggestionExtra,
  ...kSkillSuggestionProfessions,
];

/// Returns up to [maxItems] suggestions for the current query.
/// [excludeLowercase] should hold [skill.toLowerCase()] for skills already added.
Iterable<String> skillSuggestionsForQuery(
  String rawQuery, {
  required Set<String> excludeLowercase,
  int maxItems = 16,
}) {
  final q = rawQuery.trim().toLowerCase();
  if (q.isEmpty || maxItems <= 0) {
    return const Iterable.empty();
  }

  final prefix = <String>[];
  final substring = <String>[];
  final seenLower = <String>{};

  for (final skill in kSkillSuggestionPool) {
    final lower = skill.toLowerCase();
    if (excludeLowercase.contains(lower) || seenLower.contains(lower)) {
      continue;
    }
    if (lower.startsWith(q)) {
      seenLower.add(lower);
      prefix.add(skill);
    } else if (lower.contains(q)) {
      seenLower.add(lower);
      substring.add(skill);
    }
  }

  void sortAsciiCaseInsensitive(List<String> list) {
    list.sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
  }

  sortAsciiCaseInsensitive(prefix);
  sortAsciiCaseInsensitive(substring);

  return prefix.followedBy(substring).take(maxItems);
}
