// Cross-industry professional skills (business, finance, HR, healthcare, trades, etc.)

const List<String> kSkillSuggestionProfessions = [
  // Accounting & finance
  '1099 Compliance',
  'Accounts Payable',
  'Accounts Receivable',
  'Accrual Accounting',
  'AP Automation',
  'Bank Reconciliation',
  'BlackLine',
  'Bookkeeping',
  'Budget Forecasting',
  'CapEx Planning',
  'Cash Flow Analysis',
  'CFA Charterholder',
  'Chart of Accounts Design',
  'Concur',
  'Consolidation Accounting',
  'Controller Functions',
  'Corporate Tax',
  'Cost Accounting',
  'CPA',
  'Credit Management',
  'DCF Modeling',
  'Due Diligence (M&A)',
  'Expense Management',
  'External Audit Liaison',
  'Financial Close',
  'Financial Modeling (Excel)',
  'Financial Reporting',
  'Fixed Asset Accounting',
  'FP&A',
  'GAAP Compliance',
  'General Ledger',
  'Hyperion',
  'IFRS Reporting',
  'Internal Audit',
  'Inventory Accounting',
  'Invoicing',
  'Job Costing',
  'Month-End Close',
  'NetSuite ERP',
  'Payroll Accounting',
  'Procure-to-Pay',
  'Purchase Orders',
  'QuickBooks Online',
  'Revenue Recognition',
  'Risk Management',
  'Sage Intacct',
  'SOX Compliance',
  'Statutory Reporting',
  'Tax Accounting',
  'Treasury Operations',
  'Variance Analysis',
  'Xero Accounting',
  'Year-End Audit',

  // Banking, insurance & fintech
  'ACH Processing',
  'AML Compliance',
  'Anti-Fraud Systems',
  'Basel III',
  'Bond Trading Support',
  'Card Operations',
  'Claims Processing',
  'Commercial Lending',
  'Consumer Lending',
  'Credit Risk',
  'Escrow Management',
  'Foreign Exchange',
  'Investment Operations',
  'KYC Verification',
  'Loan Servicing',
  'Mortgage Origination',
  'PCI DSS',
  'Policy Underwriting',
  'Securities Operations',
  'SWIFT Messaging',
  'Trade Finance',
  'Underwriting Guidelines',
  'Wealth Management Ops',

  // Sales, BD & customer success
  'Account Planning',
  'B2B Sales',
  'B2C Sales',
  'Channel Sales',
  'Cold Outreach',
  'Contract Negotiation (Sales)',
  'CRM Hygiene',
  'Customer Onboarding',
  'Deal Desk',
  'Demo Delivery',
  'Field Sales',
  'Inside Sales',
  'Lead Qualification',
  'Negotiation',
  'Outbound Prospecting',
  'Partnership Development',
  'Pipeline Management',
  'Proposal Writing',
  'Quota Attainment',
  'Renewals Management',
  'Retail Sales',
  'RFP Responses',
  'SaaS Sales',
  'Social Selling',
  'Solution Selling',
  'Territory Management',
  'Upselling Techniques',

  // Marketing & communications
  'A/B Testing (Marketing)',
  'Affiliate Marketing',
  'Brand Guidelines',
  'Campaign Management',
  'Community Management',
  'Content Calendar',
  'Content Strategy',
  'Copywriting',
  'CRM Marketing',
  'Demand Generation',
  'Email Campaigns',
  'Event Marketing',
  'Go-to-Market Strategy',
  'Google Ads',
  'Influencer Outreach',
  'Lead Nurture Programs',
  'LinkedIn Ads',
  'Market Segmentation',
  'Marketing Analytics',
  'Marketing Automation',
  'Media Planning',
  'Meta Ads',
  'Motion Graphics Concept',
  'Newsletter Production',
  'Podcast Production',
  'Press Relations',
  'SEO Writing',
  'Social Media Strategy',
  'Webinar Programs',
  'Writing for Web',

  // HR & people ops
  '401(k) Administration',
  'ATS Administration',
  'Benefits Enrollment',
  'Candidate Screening',
  'Comp & Benefits',
  'Conflict Resolution (HR)',
  'DEI Programs',
  'E-Verify',
  'Employee Engagement',
  'Employee Relations',
  'HR Compliance',
  'HRIS Administration',
  'Interview Coaching',
  'Offer Negotiation',
  'Onboarding Programs',
  'Org Design',
  'Payroll Processing',
  'Performance Reviews',
  'Policy Writing',
  'Recruiting Coordination',
  'Succession Planning',
  'Talent Mapping',
  'Total Rewards',
  'Training Facilitation',
  'Workforce Planning',

  // Legal & compliance
  'Contract Management',
  'Corporate Governance',
  'Data Privacy (Legal)',
  'Deposition Prep',
  'Discovery Process',
  'Document Review',
  'Due Diligence (Legal)',
  'e-Discovery Tools',
  'Employment Law',
  'EU GDPR',
  'FOIA Requests',
  'Immigration Case Support',
  'IP Docketing',
  'Legal Hold',
  'LexisNexis',
  'Litigation Support',
  'NDA Drafting',
  'Notary Public',
  'Patent Landscape',
  'Regulatory Filings',
  'Trademark Clearance',
  'Westlaw Research',

  // Healthcare & life sciences
  'Aseptic Technique',
  'Biostatistics Support',
  'Bloodborne Pathogens',
  'Cerner EHR',
  'Clinical Documentation',
  'Epic EHR',
  'GMP Compliance',
  'Hand Hygiene Protocols',
  'HIPAA Privacy',
  'HIPAA Security',
  'Histotechnology',
  'ICD-10 Coding',
  'Infection Control',
  'Laboratory Safety',
  'Medical Billing',
  'Medical Terminology',
  'Meditech',
  'Patient Advocacy',
  'Patient Scheduling',
  'Peer Review Support',
  'Pharmacology Basics',
  'Prior Authorization',
  'Radiation Safety',
  'Specimen Handling',
  'Trial Monitoring',

  // Education & training
  'Adult Learning Theory',
  'Blackboard LMS',
  'Canvas LMS',
  'Classroom Technology',
  'Curriculum Mapping',
  'Differentiated Instruction',
  'Educational Assessment',
  'IEP Compliance',
  'Instructional Design',
  'Lecture Development',
  'Literacy Intervention',
  'Parent Communication',
  'Rubric Design',
  'School Administration',
  'Student Advising',
  'TESOL',
  'Training Needs Analysis',
  'Youth Mentoring',

  // Operations, supply chain & logistics
  '3PL Coordination',
  'Bill of Materials',
  'Capacity Planning',
  'Cross-Docking',
  'Demand Planning',
  'Dock Scheduling',
  'Drop Shipping',
  'FIFO Inventory',
  'Freight Auditing',
  'Import/Export Docs',
  'Inventory Control',
  'JIT Logistics',
  'Kitting Operations',
  'Last-Mile Delivery',
  'Lean Logistics',
  'Load Planning',
  'Material Requirements Planning',
  'Negotiation (Procurement)',
  'Route Optimization',
  'S&OP Planning',
  'Safety Stock Planning',
  'Supplier Scorecards',
  'Transportation Planning',
  'Vendor Sourcing',
  'Warehouse KPIs',
  'WMS Systems',

  // Manufacturing & quality
  '5S Methodology',
  '8D Problem Solving',
  'Assembly Line Balancing',
  'CAD Drafting',
  'CMM Programming',
  'CNC Operation',
  'Corrective Action (CAPA)',
  'Electrical Assembly',
  'FMEA',
  'GD&T',
  'HVAC Maintenance',
  'IPC Standards',
  'ISO 13485',
  'ISO 14001',
  'ISO 45001',
  'ISO 9001',
  'Kaizen Events',
  'Machine Setup',
  'Preventive Maintenance',
  'Process Validation',
  'PPAP',
  'Production Scheduling',
  'Quality Inspection',
  'Root Cause Analysis',
  'SPC Charts',
  'Tool & Die Support',
  'Welding (MIG/TIG)',

  // Construction & facilities
  'AutoCAD LT',
  'Blueprint Reading',
  'Building Codes Review',
  'Concrete Pouring',
  'Electrical Rough-In',
  'Equipment Rental Coord',
  'Estimator Support',
  'Framing Carpentry',
  'Jobsite Safety Walks',
  'Lift Planning',
  'Mechanical Systems',
  'Occupancy Permits',
  'OSHA 30',
  'OSHA Recordables',
  'Punch List Management',
  'Revit Modeling',
  'Roofing Systems',
  'Scheduling (Construction)',
  'Subcontractor Coordination',
  'Survey Layout',

  // Real estate & property
  'Commercial Leasing',
  'Comparative Market Analysis',
  'HOA Management',
  'Lease Administration',
  'MLS Listings',
  'Property Inspections',
  'Rent Roll Analysis',
  'Tenant Relations',
  'Vacancy Analysis',
  'Yardi Voyager',

  // Hospitality, retail & food service
  'Banquet Operations',
  'Bar Operations',
  'Cash Handling',
  'Coffee Roasting',
  'Event Coordination',
  'Food Cost Control',
  'Front of House',
  'Guest Recovery',
  'Inventory Shrink Control',
  'Line Cooking',
  'Menu Engineering',
  'Pastry Production',
  'POS Troubleshooting',
  'Restaurant POS',
  'Retail Merchandising',
  'ServSafe Manager',
  'Shift Supervision',
  'Sommelier Service',
  'Store Operations',

  // Creative & media
  'Audio Mastering Basics',
  'Color Correction',
  'DaVinci Resolve',
  'Final Cut Pro',
  'Lighting Setup',
  'Premiere Pro',
  'Pro Tools',
  'Screenwriting',
  'Storyboarding',
  'Studio Recording',
  'Voiceover Direction',

  // IT & support (non-developer)
  'Active Directory Admin',
  'Desktop Support L2',
  'DHCP/DNS Admin',
  'End-User Training',
  'Google Workspace Admin',
  'Help Desk Ticketing',
  'IT Asset Management',
  'IT Purchasing',
  'Jamf Pro',
  'Microsoft Intune',
  'Mobile Device Management',
  'Network Troubleshooting',
  'Office 365 Admin',
  'Printer Fleet Management',
  'SCCM',
  'ServiceNow ITSM',
  'Printer/Scanner Support',
  'VPN Support',
  'Windows Imaging',

  // Data & business analysis (non-engineering)
  'Cohort Analysis',
  'Dashboard Design (BI)',
  'Data Cleaning',
  'Excel PivotTables',
  'Forecast Accuracy',
  'KPI Definition',
  'Power BI',
  'SQL for Analysts',
  'Stakeholder Reporting',
  'Survey Design',
  'Tableau Desktop',

  // Government, nonprofit & grants
  '501(c)(3) Compliance',
  'CSR Reporting',
  'Donor Relations',
  'Federal Grant Writing',
  'FOIA Liaison',
  'Foundation Relations',
  'Grant Budgeting',
  'Policy Memoranda',
  'Proposal Budgets',
  'Public Hearings Support',
  'RFP Evaluation',

  // Executive & admin
  'Board Materials',
  'Calendar Management',
  'C-Suite Support',
  'Document Formatting',
  'Executive Travel Booking',
  'Meeting Minutes',
  'Office Management',
  'Presentation Design',
  'Records Retention',
  'Report Proofreading',
  'Slide Deck Narrative',
  'Vendor Invoice Coding',

  // Consulting & strategy
  'Benchmarking Studies',
  'Business Case Writing',
  'Change Management',
  'Facilitation',
  'Gap Analysis',
  'Operating Model Design',
  'Post-Merger Integration',
  'Stakeholder Workshops',
  'SWOT Analysis',
  'Time & Materials Billing',
  'Workshop Facilitation',

  // Research & academics
  'Citation Management',
  'Grant Peer Review',
  'IRB Submissions',
  'Lab Notebook Standards',
  'Literature Reviews',
  'Peer Review Writing',
  'Statistical Consulting',
  'Survey Sampling',

  // Agriculture & environment
  'Crop Scouting',
  'Environmental Sampling',
  'Erosion Control',
  'GIS Field Collection',
  'Hazardous Waste Handling',
  'Pesticide Applicator License',
  'Soil Testing',
  'Sustainability Reporting',
  'Water Quality Testing',

  // Automotive & aviation (ops)
  'Airworthiness Docs',
  'Fleet Maintenance Scheduling',
  'Ground Handling',
  'Parts Procurement (Aero)',
  'Repair Station Ops',
  'Vehicle Diagnostics',

  // Security & physical safety
  'Access Control Systems',
  'CCTV Operation',
  'Crisis Communication',
  'Emergency Response Planning',
  'Fire Watch',
  'Security Patrol',
  'Workplace Violence Prevention',

  // Languages & cross-cultural (professional)
  'Arabic (Professional)',
  'Chinese (Professional)',
  'French (Business)',
  'German (Business)',
  'Hindi (Professional)',
  'Japanese (Business)',
  'Korean (Professional)',
  'Portuguese (Professional)',
  'Spanish (Professional)',

  // Additional soft / universal
  'Active Listening',
  'Coaching Others',
  'Conflict Mediation',
  'Cross-functional Leadership',
  'Executive Communication',
  'Meeting Facilitation',
  'Presentation Skills',
  'Prioritization',
  'Stakeholder Alignment',
  'Time Management',
];
